root = "."
tmp_dir = "tmp"
test_include = [ "_test.go" ]

[build]
  # Where your main.go is located. Adjust if it's in cmd/api/main.go
  cmd = "go build -o ./tmp/main ./cmd/api/main.go"
  # Entrypoint binary relative to root. First item is the executable, more items are default arguments.
  entrypoint = ["./tmp/main"]
  # Watch these extensions
  include_ext = ["go", "tpl", "tmpl", "html", "toml"]
  # Ignore these directories
  exclude_dir = ["assets", "tmp", "vendor"]
  # Delay after saving a file before rebuilding
  delay = 1000 # ms
  # Stop scrolling log when errors happen
  stop_on_error = true
  poll = true             # <--- CRITICAL: Enables polling for Docker
  poll_interval = 500
  # Send Interrupt signal instead of Kill when reloading (graceful shutdown)
  send_interrupt = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
