services:
  api:
    container_name: gin-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Live reload magic: maps your current directory into the container
    volumes:
      - .:/usr/src/app
      - /go/pkg/mod/
    command: sh -c "go mod tidy && air"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=pass
      - DB_NAME=my_app_db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    container_name: gin-db
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=my_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
