services:
  api:
    env_file:
      - .env
    container_name: gin-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Live reload magic: maps your current directory into the container
    volumes:
      - .:/usr/src/app
      - /go/pkg/mod/
    command: sh -c "go mod tidy && air"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_KEY=${JWT_KEY}
    depends_on:
      - db

  db:
    env_file:
      - .env
    container_name: gin-db
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
