package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/ihsanpraditya/gin-clean-1/graph/model"
	model1 "github.com/ihsanpraditya/gin-clean-1/internal/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model1.User, error) {
	newUser := &model1.User{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password, // The service will hash this automatically
	}

	err := r.UserSvc.RegisterUser(ctx, newUser)
	if err != nil {
		return nil, err
	}

	return newUser, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.LoginResponse, error) {
	token, user, err := r.UserSvc.Login(ctx, email, password)
	if err != nil {
		return nil, err
	}

	return &model.LoginResponse{
		Token: token,
		User:  user,
	}, nil
}
