package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"strconv"

	"github.com/ihsanpraditya/gin-clean-1/internal/dto"
)

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, name string) (*dto.Role, error) {
	panic(fmt.Errorf("not implemented: CreateRole - createRole"))
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id string, name string) (*dto.Role, error) {
	panic(fmt.Errorf("not implemented: UpdateRole - updateRole"))
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id string) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteRole - deleteRole"))
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*dto.Role, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid role id format")
	}
	role, err := r.RoleSvc.GetRoleByID(ctx, uint(idUint))
	if err != nil {
		return nil, err
	}

	return &role, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*dto.Role, error) {
	panic(fmt.Errorf("not implemented: Roles - roles"))
}

// ID is the resolver for the id field.
func (r *roleResolver) ID(ctx context.Context, obj *dto.Role) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// Role returns RoleResolver implementation.
func (r *Resolver) Role() RoleResolver { return &roleResolver{r} }

type roleResolver struct{ *Resolver }
