package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"strconv"

	"github.com/ihsanpraditya/gin-clean-1/internal/dto"
)

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, name string) (*dto.Role, error) {
	newRole, err := r.RoleSvc.CreateRole(ctx, name)
	if err != nil {
		return nil, err
	}
	return &newRole, nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id string, name string) (*dto.Role, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid role id format")
	}
	updatedRole, err := r.RoleSvc.UpdateRole(ctx, uint(idUint), name)
	if err != nil {
		return nil, err
	}
	return &updatedRole, nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id string) (string, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return "", fmt.Errorf("invalid role id format")
	}
	err = r.RoleSvc.DeleteRole(ctx, uint(idUint))
	if err != nil {
		return "", err
	}
	
	return fmt.Sprintf("Role with ID %s successfully deleted", id), nil
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*dto.Role, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid role id format")
	}
	role, err := r.RoleSvc.GetRoleByID(ctx, uint(idUint))
	if err != nil {
		return nil, err
	}

	return &role, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*dto.Role, error) {
	roles, err := r.RoleSvc.GetAllRoles(ctx)
	if err != nil {
		return nil, err
	}

	rolesPointer := make([]*dto.Role, len(roles))
	for r := range roles {
		rolesPointer[r] = &roles[r]
	}
	
	return rolesPointer, nil
}

// ID is the resolver for the id field.
func (r *roleResolver) ID(ctx context.Context, obj *dto.Role) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// Role returns RoleResolver implementation.
func (r *Resolver) Role() RoleResolver { return &roleResolver{r} }

type roleResolver struct{ *Resolver }
