package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"strconv"

	"github.com/ihsanpraditya/gin-clean-1/graph/model"
	model1 "github.com/ihsanpraditya/gin-clean-1/internal/model"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model1.User, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id format")
	}

	updatedUser, err := r.UserSvc.UpdateUser(ctx, uint(idUint), input.Name, input.Email)
	if err != nil {
		return nil, err
	}

	return updatedUser, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (string, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return "", fmt.Errorf("invalid user id format")
	}

	err = r.UserSvc.DeleteUser(ctx, uint(idUint))
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("User with ID %s successfully deleted", id), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model1.User, error) {
	users, err := r.UserSvc.GetAllUsers(ctx)
	if err != nil {
		return nil, err
	}

	// Convert []model.User to []*model1.User
	var result []*model1.User
	for i := range users {
		result = append(result, &users[i])
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model1.User, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id format")
	}

	user, err := r.UserSvc.GetUserByID(ctx, uint(idUint))
	if err != nil {
		return nil, err
	}

	return user, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *model1.User) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
