package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"strconv"

	"github.com/ihsanpraditya/gin-clean-1/internal/dto"
	"github.com/ihsanpraditya/gin-clean-1/internal/handler"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input dto.CreateUser) (*dto.User, error) {
	if err := handler.ValidateRegisterInput(r.Resolver.Validator, &input); err != nil {
		formattedErrors := handler.FormatValidationErrors(err)

		return nil, &gqlerror.Error{
			Message: "Validation failed",
			Extensions: map[string]interface{}{
				"code":   "VALIDATION_ERROR",
				"errors": formattedErrors,
			},
		}
	}

	newUser, err := r.UserSvc.CreateUser(ctx, &input)
	if err != nil {
		return nil, err
	}

	return &newUser, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input dto.UpdateUser) (*dto.User, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id format")
	}

	updatedUser, err := r.UserSvc.UpdateUser(ctx, uint(idUint), input)
	if err != nil {
		return nil, err
	}

	return &updatedUser, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (string, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return "", fmt.Errorf("invalid user id format")
	}

	err = r.UserSvc.DeleteUser(ctx, uint(idUint))
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("User with ID %s successfully deleted", id), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*dto.User, error) {
	idUint, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id format")
	}

	user, err := r.UserSvc.GetUserByID(ctx, uint(idUint))
	if err != nil {
		return nil, err
	}

	return &user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*dto.User, error) {
	users, err := r.UserSvc.GetAllUsers(ctx)
	if err != nil {
		return nil, err
	}

	// Convert []dto.User to []*dto.User for GraphQL
	gqlUsers := make([]*dto.User, len(users))
	for i := range users {
		gqlUsers[i] = &users[i]
	}

	return gqlUsers, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *dto.User) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

func (r *createUserResolver) Roles(ctx context.Context, obj *dto.CreateUser, data []string) error {
	if obj == nil {
		return nil
	}

	roles := make([]uint, len(data))
	for i, roleIDStr := range data {
		roleID, err := strconv.ParseUint(roleIDStr, 10, 64)
		if err != nil {
			return fmt.Errorf("invalid role id format: %s", roleIDStr)
		}
		roles[i] = uint(roleID)
	}
	obj.Roles = &roles
	return nil
}

// Roles is the resolver for the roles field.
func (r *updateUserResolver) Roles(ctx context.Context, obj *dto.UpdateUser, data []string) error {
	if obj == nil {
		return nil
	}

	roles := make([]uint, len(data))
	for i, roleIDStr := range data {
		roleID, err := strconv.ParseUint(roleIDStr, 10, 64)
		if err != nil {
			return fmt.Errorf("invalid role id format: %s", roleIDStr)
		}
		roles[i] = uint(roleID)
	}
	obj.Roles = &roles
	return nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// CreateUser returns CreateUserResolver implementation.
func (r *Resolver) CreateUser() CreateUserResolver { return &createUserResolver{r} }

// UpdateUser returns UpdateUserResolver implementation.
func (r *Resolver) UpdateUser() UpdateUserResolver { return &updateUserResolver{r} }

type (
	userResolver       struct{ *Resolver }
	createUserResolver struct{ *Resolver }
	updateUserResolver struct{ *Resolver }
)
