// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var Role = struct {
	ID        field.Number[uint]
	Name      field.String
	CreatedAt field.Time
	UpdatedAt field.Time
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	Name:      field.String{}.WithColumn("name"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
}
