// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"github.com/ihsanpraditya/gin-clean-1/internal/model"
	"gorm.io/cli/gorm/field"
)

var User = struct {
	ID        field.Number[uint]
	Name      field.String
	Email     field.String
	Password  field.String
	Roles     field.Slice[model.Role]
	IsActive  field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	Name:      field.String{}.WithColumn("name"),
	Email:     field.String{}.WithColumn("email"),
	Password:  field.String{}.WithColumn("password"),
	Roles:     field.Slice[model.Role]{}.WithName("Roles"),
	IsActive:  field.Bool{}.WithColumn("is_active"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
}
