// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var User = struct {
	ID       field.Number[uint]
	Name     field.String
	Email    field.String
	Password field.String
}{
	ID:       field.Number[uint]{}.WithColumn("id"),
	Name:     field.String{}.WithColumn("name"),
	Email:    field.String{}.WithColumn("email"),
	Password: field.String{}.WithColumn("password"),
}
